spring.application.name=twitter.clone
server.port=3200

spring.datasource.url=jdbc:postgresql://localhost:5432/twitterdb
spring.datasource.username=postgres
spring.datasource.password=tug.cek.com00
spring.jpa.properties.hibernate.default_schema=twitter_schema

